"""Tests for the record parser, the histogram helpers and the capture writer.

fixtures/stats_sample.jsonl is generated by the C++ test binary:

    build/tests/pot_tests.exe --emit-fixtures host/potluck/tests/fixtures

so these tests run against exactly the bytes a board emits, not against a
description of them. Regenerate it whenever stats_json.cpp changes -- and if a
test here then fails, the format changed and potluck-capture has to be updated to
match, which is the point.

Run with:  python -m pytest host/potluck/tests -q
       or:  python host/potluck/tests/test_records.py
"""

from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from potluck import frame as fr  # noqa: E402
from potluck import link_stats as ls  # noqa: E402
from potluck.capture import CaptureWriter, read_capture  # noqa: E402
from potluck.live import Monitor  # noqa: E402
from potluck.records import FrameRecord, LogLine, Record, RecordStream, ppm_to_percent  # noqa: E402

FIXTURE = Path(__file__).parent / "fixtures" / "stats_sample.jsonl"


def _fixture_lines() -> list[str]:
    assert FIXTURE.exists(), (
        f"{FIXTURE} is missing. Generate it with:\n"
        "  build/tests/pot_tests.exe --emit-fixtures host/potluck/tests/fixtures"
    )
    return [ln for ln in FIXTURE.read_text(encoding="utf-8").splitlines() if ln.strip()]


# --------------------------------------------------------------------------------------------
# The firmware's real output
# --------------------------------------------------------------------------------------------


def test_every_fixture_line_is_valid_json_with_a_type():
    for line in _fixture_lines():
        obj = json.loads(line)  # raises if the firmware emitted anything malformed
        assert isinstance(obj, dict)
        assert "t" in obj, obj


def test_the_stream_recognises_every_record_the_firmware_emits():
    stream = RecordStream()
    kinds: list[str] = []
    for line in _fixture_lines():
        item = stream.feed(line)
        assert isinstance(item, Record), f"not recognised as a record: {line[:80]}"
        kinds.append(item.kind)

    assert stream.stats.bad_json == 0
    assert stream.stats.logs == 0
    # An unrecognised record type means the firmware emits something this tool
    # would silently ignore.
    assert stream.stats.unknown_kinds == {}, stream.stats.unknown_kinds
    assert set(kinds) == {"boot", "link", "node", "event"}


def test_boot_record_carries_the_section_6_measurement():
    stream = RecordStream()
    boot = next(
        item for line in _fixture_lines()
        if isinstance(item := stream.feed(line), Record) and item.kind == "boot"
    )
    dram = boot["dram"]
    # The derived figures are computed on the node so the host cannot get the
    # subtraction backwards; check they agree with the raw readings anyway.
    assert dram["wifi_stack"] == dram["after_netif"] - dram["after_wifi_start"]
    assert dram["espnow"] == dram["after_wifi_start"] - dram["after_espnow"]
    assert dram["total_to_radio"] == dram["at_boot"] - dram["after_espnow"]
    # section 8.2's numbers survive the round trip.
    assert boot["hb_period_ms"] == 100
    assert boot["hb_miss_limit"] == 6
    assert boot["hb_period_ms"] * boot["hb_miss_limit"] == 600


def test_link_record_never_claims_a_one_way_delay():
    # The commitment in firmware/components/pot_link/include/pot/link_stats.hpp,
    # checked against the emitted bytes rather than against the source comment.
    for line in _fixture_lines():
        obj = json.loads(line)
        if obj.get("t") != "link":
            continue
        text = json.dumps(obj)
        for forbidden in ("one_way", "oneway", "owd", "latency_us"):
            assert forbidden not in text, f"{forbidden} appeared in a link record"
        rtt = obj["rtt"]
        # Every duration names the clock it was measured on.
        assert "remote_turnaround_us" in rtt
        assert "txq_last_us" in rtt


def test_unmeasured_values_arrive_as_null_and_stay_none():
    stream = RecordStream()
    fresh = [
        item for line in _fixture_lines()
        if isinstance(item := stream.feed(line), Record)
        and item.kind == "link"
        and item.get("state") == "known"
    ]
    assert fresh, "the fixture should include a link with nothing measured yet"
    v = fresh[0]
    assert v["tx"]["pdr_ppm"] is None
    assert v["rx"]["pdr_ppm"] is None
    assert v["rtt"]["min_us"] is None
    assert v["rtt"]["p50_us"] is None
    # And a None ratio must not become 0.0% on the way to the display.
    assert ppm_to_percent(v["tx"]["pdr_ppm"]) is None
    assert ppm_to_percent(0) == 0.0  # a measured zero is still zero


def test_percentiles_agree_with_the_firmwares_own_computation():
    # The node ships bucket counts and its own p50/p99. Recomputing them here from
    # the counts is what keeps link_stats.py's bucket edges in step with the
    # firmware's: if the edges drifted, these would disagree.
    stream = RecordStream()
    checked = 0
    for line in _fixture_lines():
        item = stream.feed(line)
        if not isinstance(item, Record) or item.kind != "link":
            continue
        rtt = item["rtt"]
        hist = rtt.get("hist")
        if not hist or sum(hist) == 0:
            continue
        for pct, key in ((50, "p50_us"), (99, "p99_us")):
            ours = ls.percentile(hist, pct)
            theirs = rtt[key]
            assert ours is not None and theirs is not None
            assert list(ours) == list(theirs), f"p{pct}: host {ours} vs node {theirs}"
        checked += 1
    assert checked > 0, "no populated histogram in the fixture"


def test_ppm_conversion():
    assert ppm_to_percent(1_000_000) == 100.0
    assert ppm_to_percent(991_983) == 99.1983
    assert ppm_to_percent(None) is None


# --------------------------------------------------------------------------------------------
# Histogram helpers
# --------------------------------------------------------------------------------------------


def test_bucket_edges_are_monotonic_and_cover_everything():
    for i in range(1, ls.RTT_BUCKETS):
        assert ls.RTT_BUCKET_EDGE_US[i] > ls.RTT_BUCKET_EDGE_US[i - 1]
    assert ls.RTT_BUCKET_EDGE_US[-1] == 0xFFFFFFFF
    assert ls.bucket_bounds(0) == (0, 1000)
    assert ls.bucket_bounds(ls.RTT_BUCKETS - 1)[1] is None


def test_bucket_of_matches_the_firmware_rule():
    # A sample equal to an edge belongs to that bucket; one more goes to the next.
    assert ls.bucket_of(0) == 0
    assert ls.bucket_of(1000) == 0
    assert ls.bucket_of(1001) == 1
    assert ls.bucket_of(2000) == 1
    assert ls.bucket_of(500_000) == ls.RTT_BUCKETS - 1
    # section 3's measured figures all land inside the finite range.
    for us in (2783, 3462, 7851, 25628, 59192, 103850):
        assert ls.bucket_of(us) < ls.RTT_BUCKETS - 1


def test_percentile_is_an_interval_and_empty_is_none():
    assert ls.percentile([0] * 16, 50) is None
    h = [0] * 16
    h[2] = 90    # (2000, 3000]
    h[11] = 10   # (42000, 60000]
    assert ls.percentile(h, 50) == (2000, 3000)
    assert ls.percentile(h, 90) == (2000, 3000)
    assert ls.percentile(h, 99) == (42000, 60000)
    assert ls.percentile(h, 100) == (42000, 60000)


def test_mean_is_bounded_not_invented():
    h = [0] * 16
    h[2] = 1  # (2000, 3000]
    lo, hi = ls.mean_bounds(h)
    assert lo == 2000.0 and hi == 3000.0

    # An occupied overflow bucket makes the mean unbounded above, and saying so
    # beats picking a number for it.
    h2 = [0] * 16
    h2[15] = 1
    lo2, hi2 = ls.mean_bounds(h2)
    assert hi2 is None
    assert ls.mean_bounds([0] * 16) is None


def test_describe_bucket_reads_sensibly():
    assert ls.describe_bucket(0) == "0.0-1.0 ms"
    assert ls.describe_bucket(2) == "2.0-3.0 ms"
    assert ls.describe_bucket(15) == ">200 ms"


# --------------------------------------------------------------------------------------------
# Robustness
# --------------------------------------------------------------------------------------------


def test_a_truncated_line_is_counted_and_skipped_not_guessed_at():
    stream = RecordStream()
    good = _fixture_lines()[1]
    item = stream.feed(good[: len(good) // 2])
    assert isinstance(item, LogLine)  # kept as evidence, not parsed
    assert stream.stats.bad_json == 1
    assert stream.stats.records == 0

    # And the next good line still parses: one bad line must not poison the stream.
    assert isinstance(stream.feed(good), Record)


def test_node_log_lines_pass_through():
    stream = RecordStream()
    item = stream.feed("I (1234) pot.m0: peer 0xcdef declared DEAD after 6 misses")
    assert isinstance(item, LogLine)
    assert stream.stats.logs == 1
    assert stream.feed("") is None
    assert stream.feed("   ") is None


def test_json_that_is_not_one_of_our_records():
    stream = RecordStream()

    # An object without a "t" field looked like a record and was not one, so it
    # counts as malformed: something upstream is emitting the wrong shape.
    assert isinstance(stream.feed('{"no_type_field":1}'), LogLine)
    assert stream.stats.bad_json == 1

    # A line that never claimed to be a record is just text. Counting it as
    # malformed would make the bad_json figure useless for spotting a real
    # problem, because a node's log would inflate it constantly.
    assert isinstance(stream.feed("[1,2,3]"), LogLine)
    assert stream.stats.bad_json == 1
    assert stream.stats.logs == 1


def test_frame_records_decode_and_bad_ones_are_kept_with_a_reason():
    raw = fr.encode(src=1, dst=2, opcode=fr.Op.HEARTBEAT, payload=bytes(48), ack_req=True)
    stream = RecordStream()
    item = stream.feed(json.dumps({
        "t": "frame", "at_us": 12345, "dir": "rx",
        "peer": "24:6f:28:ab:cd:ef", "rssi": -70, "len": len(raw), "raw": raw.hex(),
    }))
    assert isinstance(item, FrameRecord)
    assert item.decoded is not None
    assert item.decoded.opcode == fr.Op.HEARTBEAT
    assert item.direction == "rx" and item.rssi == -70
    assert item.error is None

    # A frame the node rejected still belongs in the capture, with its reason.
    bad = stream.feed(json.dumps({"t": "frame", "dir": "rx", "raw": "00" * 20}))
    assert isinstance(bad, FrameRecord)
    assert bad.decoded is None
    assert bad.error and "bad_magic" in bad.error
    assert stream.stats.bad_frames == 1

    # Non-hex must not raise.
    ugly = stream.feed(json.dumps({"t": "frame", "dir": "tx", "raw": "not-hex"}))
    assert isinstance(ugly, FrameRecord) and ugly.raw == b""


# --------------------------------------------------------------------------------------------
# Capture writer -- section 7.6
# --------------------------------------------------------------------------------------------


def test_capture_round_trip_keeps_the_host_timestamp_and_the_raw_frame():
    raw = fr.encode(src=1, dst=2, opcode=fr.Op.HEARTBEAT, payload=bytes(48))
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "cap.jsonl"
        with CaptureWriter(path) as w:
            w.write_frame(node_id=258, direction="rx", raw=raw,
                          peer_mac="24:6f:28:ab:cd:ef", rssi=-70,
                          node_ts_us=999, host_ts=1_700_000_000.5)
            w.write_record("link", {"node": 258, "peer": 9}, host_ts=1_700_000_001.0)
            w.write_log("I (1) pot.m0: hello", host_ts=1_700_000_002.0)

        rows = list(read_capture(path))
        assert len(rows) == 3
        # section 7.6: host timestamp, direction, raw frame.
        assert rows[0]["host_ts"] == 1_700_000_000.5
        assert rows[0]["dir"] == "rx"
        assert bytes.fromhex(rows[0]["raw"]) == raw
        # The node's own clock is kept too, and labelled as the node's.
        assert rows[0]["node_ts_us"] == 999
        assert rows[1]["rec"] == "link" and rows[1]["peer"] == 9
        assert rows[2]["rec"] == "log"

        # A capture must be re-readable as a frame stream.
        assert fr.parse(bytes.fromhex(rows[0]["raw"])).opcode == fr.Op.HEARTBEAT


def test_capture_rotates_by_size():
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "cap.jsonl"
        with CaptureWriter(path, rotate_bytes=512) as w:
            for i in range(200):
                w.write_record("node", {"node": 1, "i": i})
        files = sorted(p.name for p in Path(tmp).iterdir())
        assert len(files) > 1, files
        assert "cap.jsonl" in files
        total = sum(len(list(read_capture(Path(tmp) / f))) for f in files)
        assert total == 200


def test_capture_survives_a_truncated_final_line():
    # A soak that ends in a power cut leaves a half-written line. Everything before
    # it is still worth having.
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "cap.jsonl"
        with CaptureWriter(path) as w:
            w.write_record("node", {"node": 1})
            w.write_record("node", {"node": 2})
        with open(path, "a", encoding="utf-8") as fh:
            fh.write('{"host_ts":1.0,"kind":"nod')
        rows = list(read_capture(path))
        assert len(rows) == 2


def test_compressed_capture():
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "cap.jsonl"
        with CaptureWriter(path, compress=True) as w:
            w.write_record("node", {"node": 7})
        written = list(Path(tmp).iterdir())
        assert written and written[0].suffix == ".gz"
        assert list(read_capture(written[0]))[0]["node"] == 7


# --------------------------------------------------------------------------------------------
# The summary the M0 acceptance check reads
# --------------------------------------------------------------------------------------------


def test_monitor_summary_reports_what_section_13_M0_asks_for():
    monitor = Monitor()
    stream = RecordStream()
    for line in _fixture_lines():
        item = stream.feed(line)
        if isinstance(item, Record):
            monitor.on_record(item.kind, item.data)

    text = monitor.summary()

    # A PDR figure and a delay histogram, both measured.
    assert "PDR" in text
    assert "delay histogram" in text
    assert "2.0-3.0 ms" in text  # a populated bucket, rendered from its edges
    # section 6's [MEASURE] item.
    assert "[MEASURE]" in text
    assert "Wi-Fi stack cost" in text
    # And the honesty note travels with the histogram.
    assert "no one-way measurement" in text
    assert "one_way" not in text.replace("no one-way measurement", "")
    # An unmeasured link says so rather than reporting zero.
    assert "unmeasured" in text


def test_monitor_surfaces_membership_transitions_immediately():
    monitor = Monitor()
    out = monitor.on_record("event", {"at_ms": 601, "node": 258, "kind": "peer_dead",
                                      "peer": 0xCDEF, "slot": 0, "a": 6, "b": 600})
    assert out is not None and "peer_dead" in out
    # A routine event should not interrupt the display.
    assert monitor.on_record("event", {"at_ms": 1, "node": 258, "kind": "peer_discovered",
                                       "peer": 1, "slot": 0, "a": 0, "b": 0}) is None


def test_monitor_boot_line_flags_a_wifi_stack_over_section_6s_expectation():
    monitor = Monitor()
    out = monitor.on_record("boot", {
        "node": 1, "epoch": 1, "mac": "aa:bb:cc:dd:ee:ff", "espnow_ver": 2, "chan": 1,
        "hb_period_ms": 100, "hb_miss_limit": 6, "fw": "m0", "idf": "v6.0.2",
        "dram": {"wifi_stack": 50 * 1024, "espnow": 2048},
    })
    assert out is not None and "ABOVE" in out and "RX ring shrinks first" in out

    ok = monitor.on_record("boot", {
        "node": 2, "epoch": 1, "mac": "aa:bb:cc:dd:ee:00", "espnow_ver": 2, "chan": 1,
        "hb_period_ms": 100, "hb_miss_limit": 6, "fw": "m0", "idf": "v6.0.2",
        "dram": {"wifi_stack": 30 * 1024, "espnow": 2048},
    })
    assert ok is not None and "ABOVE" not in ok


def test_monitor_table_renders_with_no_data_and_with_data():
    monitor = Monitor()
    assert "no links yet" in monitor.table()
    stream = RecordStream()
    for line in _fixture_lines():
        item = stream.feed(line)
        if isinstance(item, Record):
            monitor.on_record(item.kind, item.data)
    table = monitor.table()
    assert "0x0102" in table
    assert "--" in table  # the unmeasured link's PDR


if __name__ == "__main__":
    failures = 0
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            try:
                fn()
                print(f"ok   {name}")
            except Exception as exc:  # noqa: BLE001
                failures += 1
                print(f"FAIL {name}: {type(exc).__name__}: {exc}")
    print(f"\n{failures} failure(s)")
    sys.exit(1 if failures else 0)
