// M8.1: this firmware's registration table -- every actor type it can run, one row each.
//
// Adding an actor type means: a class against pot/actor.hpp, its config format in pot/deploy.hpp
// (so images can name it), and one row in actor_table.cpp. Nothing in m0_main.cpp.

#pragma once

#include <cstddef>

#include "pot/actor.hpp"
#include "pot/deploy.hpp"

namespace pot {

namespace app {
// The firmware's whole table: Potluck's built-in rows, then every external component's (M8.2, PS-1).
// Merged on the first call; a refused merge (two rows for one type, an external row below 0x80)
// is logged naming both components, and the table is then the built-ins only.
const ActorKind* actor_table(size_t* n);

// Generated by main/CMakeLists.txt from the components given to -AppComponents (app_rows.cpp).
extern const AppRows kAppRows[];
extern const size_t kAppRowsLen;
}  // namespace app

// The few board services an actor may need that are not the node's. m0_main.cpp provides them.
namespace board {
// What "healthy" looks like on the status LED (M3). Blue, yellow and red keep their diagnostic
// meanings whatever is deployed.
void set_led_healthy(const LedConfig& c);
}  // namespace board

}  // namespace pot
