"""M7: compile the guests in guests/ to WebAssembly, as a vendor would.

    python tools/build_guests.py          # guests/*.rs (except the API) -> guests/build/<name>.wasm,
                                          # and tests' copy: firmware/components/pot_wasm/include/pot/guest_examples.h

Rust's wasm32-unknown-unknown target, no_std, no allocator, built for the WebAssembly MVP feature set
(`-C target-cpu=mvp`) -- the interpreter (wasm3 v0.9.0) is not asked to parse anything newer. One 64 KiB
page of memory with an 8 KiB stack inside it: what the sandbox allows a guest by default.
"""

from __future__ import annotations

import os
import subprocess
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = os.path.join(ROOT, "guests")
OUT = os.path.join(SRC, "build")
HEADER = os.path.join(ROOT, "firmware", "components", "pot_wasm", "include", "pot", "guest_examples.h")
FLAGS = ["--target", "wasm32-unknown-unknown", "--crate-type", "cdylib", "--edition", "2021",
         "-C", "opt-level=s", "-C", "panic=abort", "-C", "target-cpu=mvp", "-C", "strip=symbols",
         "-C", "link-arg=--initial-memory=65536", "-C", "link-arg=--max-memory=65536",
         "-C", "link-arg=-zstack-size=8192"]


def main() -> int:
    os.makedirs(OUT, exist_ok=True)
    built = {}
    for f in sorted(os.listdir(SRC)):
        if not f.endswith(".rs") or f == "potluck_guest.rs":
            continue
        name = f[:-3]
        out = os.path.join(OUT, name + ".wasm")
        r = subprocess.run(["rustc", *FLAGS, "-o", out, os.path.join(SRC, f)], capture_output=True, text=True)
        if r.returncode != 0:
            print(r.stderr, file=sys.stderr)
            return 1
        built[name] = open(out, "rb").read()
        print(f"{name:16s} {len(built[name]):6d} B")
    lines = ["// Generated by tools/build_guests.py from guests/*.rs (M7). Do not edit.", "#pragma once", "",
             "#include <cstdint>", "", "namespace pot {", "namespace guest_examples {", ""]
    for name, data in built.items():
        lines.append(f"inline constexpr uint8_t k_{name}[] = {{{', '.join(f'0x{b:02x}' for b in data)}}};")
    lines += ["", "}  // namespace guest_examples", "}  // namespace pot", ""]
    with open(HEADER, "w", encoding="ascii", newline="\n") as fh:
        fh.write("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
