"""Parse the serial record stream a node emits.

One JSON object per line, per firmware/components/pot_link/include/pot/stats_json.hpp.
The lines a board actually produces are checked into tests/fixtures/stats_sample.jsonl,
generated by the C++ test binary, so this module is tested against the firmware's
real output rather than against a description of it.

Two robustness rules, both because a serial line drops characters:

  * A line that is not valid JSON is counted and skipped, never guessed at. The
    board's own emitter refuses to print a truncated line, so a malformed line
    here means the *wire* lost bytes, and the only honest thing to do with a
    partial record is discard it.
  * Anything that is not one of our records -- ESP-IDF log lines, boot ROM
    chatter -- passes through as a LogLine rather than being an error. A node's
    log is evidence too.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

from . import frame as fr


@dataclass(slots=True)
class LogLine:
    """A non-record line: ESP-IDF logging, bootloader output, anything else."""

    text: str


@dataclass(slots=True)
class Record:
    """A parsed record. `kind` is the "t" field; `data` is the rest verbatim."""

    kind: str
    data: dict[str, Any]

    def __getitem__(self, key: str) -> Any:
        return self.data[key]

    def get(self, key: str, default: Any = None) -> Any:
        return self.data.get(key, default)


@dataclass(slots=True)
class FrameRecord:
    """A teed frame (CONFIG_POT_FRAME_TEE), with its bytes decoded.

    `decoded` is None when the bytes did not parse -- which is itself worth
    recording, because a frame the node rejected is a frame the capture should
    still contain.
    """

    node_ts_us: int
    direction: str
    peer_mac: str
    rssi: int
    raw: bytes
    decoded: fr.Frame | None
    error: str | None


#: Record kinds this tool understands, matching the `"t"` values the firmware emits from
#: firmware/components/pot_link/src/stats_json.cpp and m0_main.cpp's emit_ns_records().
#:
#: Kept as one named set rather than inline, because it is the version-skew boundary: a kind not
#: listed here is reported as "firmware newer than this tool", and that warning is only useful if the
#: list is maintained. `ns` was missed when M1 added emit_ns_records(), so a real capture warned about
#: its own node's namespace -- which is exactly the false alarm that teaches people to ignore warnings.
KNOWN_KINDS = frozenset({"boot", "link", "node", "event", "ns"})


@dataclass(slots=True)
class ParseStats:
    lines: int = 0
    records: int = 0
    frames: int = 0
    logs: int = 0
    bad_json: int = 0
    bad_frames: int = 0
    unknown_kinds: dict[str, int] = field(default_factory=dict)


class RecordStream:
    """Turn lines of serial text into records, frames and log lines."""

    def __init__(self) -> None:
        self.stats = ParseStats()

    def feed(self, line: str) -> LogLine | Record | FrameRecord | None:
        """Parse one line. Returns None only for a blank line."""
        self.stats.lines += 1
        text = line.strip()
        if not text:
            return None

        # Cheap pre-filter: ESP-IDF log lines never start with '{', and trying
        # json.loads on every one of them is measurable at 921600 baud.
        if not text.startswith("{"):
            self.stats.logs += 1
            return LogLine(text)

        try:
            obj = json.loads(text)
        except json.JSONDecodeError:
            self.stats.bad_json += 1
            return LogLine(text)

        if not isinstance(obj, dict) or "t" not in obj:
            self.stats.bad_json += 1
            return LogLine(text)

        kind = obj.pop("t")
        if kind == "frame":
            return self._frame(obj)

        self.stats.records += 1
        if kind not in KNOWN_KINDS:
            self.stats.unknown_kinds[kind] = self.stats.unknown_kinds.get(kind, 0) + 1
        return Record(kind=kind, data=obj)

    def _frame(self, obj: dict[str, Any]) -> FrameRecord:
        self.stats.frames += 1
        raw_hex = obj.get("raw", "")
        try:
            raw = bytes.fromhex(raw_hex)
        except ValueError:
            self.stats.bad_frames += 1
            raw = b""

        decoded: fr.Frame | None = None
        error: str | None = None
        if raw:
            try:
                decoded = fr.parse(raw)
            except fr.FrameError as exc:
                self.stats.bad_frames += 1
                error = str(exc)

        return FrameRecord(
            node_ts_us=int(obj.get("at_us", 0)),
            direction=str(obj.get("dir", "?")),
            peer_mac=str(obj.get("peer", "")),
            rssi=int(obj.get("rssi", 0)),
            raw=raw,
            decoded=decoded,
            error=error,
        )


def ppm_to_percent(ppm: int | None) -> float | None:
    """Convert the firmware's parts-per-million ratios to a percentage.

    The firmware emits ppm because it has no business formatting floats; the
    display side is where a percentage belongs. None propagates: an unmeasured
    ratio must not become 0.0%.
    """
    return None if ppm is None else ppm / 10_000.0
