"""Serial framing, mirroring firmware/components/pot_frame/src/serial_framing.cpp.

ARCHITECTURE.md section 5.3: "USB-serial / UART | 1446 B | COBS framing + CRC-16". This is the host
half of that, and it is the layer M2's `potluck-bridge` speaks.

Third independent implementation in this project, and for the same reason as the first two: a codec
that only exists once can be tested for self-consistency and nothing more. tests/test_serial.py
replays a corpus generated by the C++ side and requires byte-identical agreement.

The CRC variant is pinned rather than left to "CRC-16", which names a dozen incompatible algorithms:

    CRC-16/CCITT-FALSE   poly 0x1021, init 0xFFFF, no reflection, no final XOR

Two implementations that each correctly implement a *different* CRC-16 reject each other's frames
forever, and the symptom is a link that looks dead rather than wrong.
"""

from __future__ import annotations

from typing import Callable, Iterator

CRC16_INIT = 0xFFFF
CRC16_POLY = 0x1021
DELIMITER = 0x00
CRC_BYTES = 2

ESPNOW_V2_LINK_MTU = 1470


def cobs_max_encoded(n: int) -> int:
    """Worst-case encoded size, excluding the delimiter."""
    return n + n // 254 + 1


SERIAL_FRAME_MAX = cobs_max_encoded(ESPNOW_V2_LINK_MTU + CRC_BYTES) + 1


def crc16(data: bytes, seed: int = CRC16_INIT) -> int:
    """CRC-16/CCITT-FALSE. Check value for b"123456789" is 0x29B1."""
    crc = seed
    for b in data:
        crc ^= b << 8
        for _ in range(8):
            crc = ((crc << 1) ^ CRC16_POLY) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


def cobs_encode(data: bytes) -> bytes:
    """Encode so the result contains no zero byte. Does not append the delimiter."""
    out = bytearray()
    code_at = 0
    out.append(0)  # placeholder for the first code byte
    code = 1
    for b in data:
        if b == 0:
            out[code_at] = code
            code_at = len(out)
            out.append(0)
            code = 1
        else:
            out.append(b)
            code += 1
            if code == 0xFF:
                # A run of 254 non-zero bytes: emit the maximum code and start a new group. This is
                # where COBS's one-byte-per-254 overhead comes from, and the classic off-by-one.
                out[code_at] = code
                code_at = len(out)
                out.append(0)
                code = 1
    out[code_at] = code
    return bytes(out)


def cobs_decode(data: bytes) -> bytes | None:
    """Decode, or None if the sequence is malformed.

    Returns None rather than a best effort: a decoder that clamped an overrunning group would
    silently produce a short frame and leave the CRC to catch it, which is a worse failure than
    saying so.
    """
    out = bytearray()
    i = 0
    n = len(data)
    if n == 0:
        return None
    while i < n:
        code = data[i]
        if code == 0:
            return None  # a zero inside the body is not COBS
        i += 1
        if i + code - 1 > n:
            return None  # the group claims more bytes than remain
        out += data[i : i + code - 1]
        i += code - 1
        if code != 0xFF and i < n:
            out.append(0)
    return bytes(out)


def write_serial_frame(frame: bytes) -> bytes:
    """Wrap a Potluck Frame for the wire: COBS(frame || crc16-le) followed by 0x00.

    The CRC covers the Potluck Frame and is computed before COBS, so it protects the payload rather than
    the encoding.
    """
    if not frame:
        raise ValueError("empty frame")
    c = crc16(frame)
    staged = frame + bytes((c & 0xFF, (c >> 8) & 0xFF))
    return cobs_encode(staged) + bytes((DELIMITER,))


class SerialError(Exception):
    """A chunk between two delimiters that is not a valid frame."""

    def __init__(self, reason: str) -> None:
        super().__init__(reason)
        self.reason = reason


def read_serial_frame(chunk: bytes) -> bytes:
    """Unwrap one COBS chunk, or raise SerialError. Reasons match the firmware's strings."""
    if not chunk:
        raise SerialError("empty")
    if len(chunk) > SERIAL_FRAME_MAX:
        raise SerialError("too_long")
    staged = cobs_decode(chunk)
    if staged is None:
        raise SerialError("cobs_invalid")
    if len(staged) < CRC_BYTES:
        raise SerialError("too_short")
    body, tail = staged[:-CRC_BYTES], staged[-CRC_BYTES:]
    want = tail[0] | (tail[1] << 8)
    if crc16(body) != want:
        raise SerialError("bad_crc")
    return body


class SerialReassembler:
    """Turn a byte stream into frames.

    Resynchronisation is the point: a host that opens the port while a node is already talking
    starts mid-frame, and the first delimiter it sees ends a partial frame that fails its CRC. That
    is expected, so it is counted rather than raised.
    """

    def __init__(self) -> None:
        self.reset()

    def reset(self) -> None:
        self._buf = bytearray()
        self._overflow = False
        self.frames_ok = 0
        self.bad_crc = 0
        self.cobs_invalid = 0
        self.too_long = 0
        self.empty = 0
        self.bytes_in = 0

    def feed(self, data: bytes) -> Iterator[bytes]:
        """Yield each complete, valid frame in `data`."""
        self.bytes_in += len(data)
        for b in data:
            if b != DELIMITER:
                if len(self._buf) < SERIAL_FRAME_MAX:
                    self._buf.append(b)
                else:
                    # Longer than any legal frame. Keep consuming to the next delimiter rather than
                    # emitting garbage; the stream recovers at the next boundary.
                    self._overflow = True
                continue

            if self._overflow:
                self.too_long += 1
            elif not self._buf:
                self.empty += 1  # two delimiters in a row, or the first byte after attaching
            else:
                try:
                    frame = read_serial_frame(bytes(self._buf))
                except SerialError as exc:
                    if exc.reason == "bad_crc":
                        self.bad_crc += 1
                    elif exc.reason == "too_long":
                        self.too_long += 1
                    elif exc.reason == "empty":
                        self.empty += 1
                    else:
                        self.cobs_invalid += 1
                else:
                    self.frames_ok += 1
                    yield frame
            self._buf.clear()
            self._overflow = False

    def feed_to(self, data: bytes, on_frame: Callable[[bytes], None]) -> None:
        for f in self.feed(data):
            on_frame(f)

    @property
    def stats(self) -> dict[str, int]:
        return {
            "frames_ok": self.frames_ok,
            "bad_crc": self.bad_crc,
            "cobs_invalid": self.cobs_invalid,
            "too_long": self.too_long,
            "empty": self.empty,
            "bytes_in": self.bytes_in,
        }
